default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: alisa
  password: lolwer11
  host: localhost

development:
  <<: *default
  database: VetelinarClinika_development

test:
  <<: *default
  database: VetelinarClinika_test

production:
  <<: *default
  database: VetelinarClinika_production
  username: alisa
  password: lolwer11
  host: localhost

